# Version 1.8.0
[versions."1.8.0".local-images]
stackable-devel = "1.0.0"
vector = "0.52.0"

[versions."1.8.0".build-arguments]
golang-version = "1.24.6"

# Version 1.12.3
[versions."1.12.3".local-images]
stackable-devel = "1.0.0"
vector = "0.52.0"

[versions."1.12.3".build-arguments]
golang-version = "1.24.6"
