[versions."1.28.1".local-images]
java-base = "11"
java-devel = "11"
"shared/logback" = "1.3.14" # https://github.com/apache/nifi/blob/rel/nifi-1.28.1/pom.xml#L146

[versions."1.28.1".build-arguments]
git-sync-version = "v4.4.1"
# Check for new versions at the upstream: https://github.com/stackabletech/nifi-opa-plugin/tags
# Checkout a Patchable version (patch-series) for the new tag
nifi-opa-authorizer-plugin-version = "0.4.0"

[versions."2.6.0".local-images]
java-base = "21"
java-devel = "21"
"shared/logback" = "1.5.18" # https://github.com/apache/nifi/blob/rel/nifi-2.6.0/pom.xml#L156

[versions."2.6.0".build-arguments]
git-sync-version = "v4.4.1"
# Check for new versions at the upstream: https://github.com/stackabletech/nifi-opa-plugin/tags
# Checkout a Patchable version (patch-series) for the new tag
nifi-opa-authorizer-plugin-version = "0.4.0"

# Release a new version here: https://github.com/stackabletech/nifi-iceberg-bundle
# Checkout a Patchable version (patch-series) for the new tag
nifi-iceberg-bundle-version = "0.0.5"

[versions."2.7.2".local-images]
java-base = "21" # As stated in GitHub README
java-devel = "21"
"shared/logback" = "1.5.24" # https://github.com/apache/nifi/blob/rel/nifi-2.7.2/pom.xml#L167

[versions."2.7.2".build-arguments]
git-sync-version = "v4.4.1"
# Check for new versions at the upstream: https://github.com/stackabletech/nifi-opa-plugin/tags
# Checkout a Patchable version (patch-series) for the new tag
nifi-opa-authorizer-plugin-version = "0.4.0"
