[versions."1.3.0-fd5a5fb-hbase2.6.3".local-images]
"hadoop/hadoop" = "3.4.2"
"hbase/hbase" = "2.6.3"
"java-devel" = "11"

[versions."1.3.0-fd5a5fb-hbase2.6.3".build-arguments]
hbase-operator-tools-version = "1.3.0-fd5a5fb"
hbase-thirdparty-version = "4.1.9"
delete-caches = "true"
