# Not part of SDP 25.7.0, but still required for hbase, hive, spark-k8s
[versions."3.3.6".local-images]
"hadoop/hadoop" = "3.3.6"
java-base = "11"
java-devel = "11"

[versions."3.3.6".build-arguments]
async-profiler-version = "2.9"
jmx-exporter-version = "1.3.0"
hdfs-utils-version = "0.4.0"

[versions."3.4.2".local-images]
"hadoop/hadoop" = "3.4.2"
java-base = "11"
java-devel = "11"

[versions."3.4.2".build-arguments]
async-profiler-version = "2.9"
jmx-exporter-version = "1.3.0"
hdfs-utils-version = "0.4.2"
