[versions."477".local-images]
java-base = "24"
"trino/trino" = "477"
"trino/storage-connector" = "477"

[versions."477".build-arguments]
jmx-exporter-version = "1.3.0"

[versions."479".local-images]
java-base = "25"
"trino/trino" = "479"
"trino/storage-connector" = "477"
# There is no 479 connector yet
# "trino/storage-connector" = "479"

[versions."479".build-arguments]
jmx-exporter-version = "1.3.0"
