[versions."2.9.3".local-images]
"shared/statsd-exporter" = "0.28.0"
vector = "0.49.0"
stackable-devel = "1.0.0"

[versions."2.9.3".build-arguments]
python-version = "3.9"
git-sync-version = "v4.4.1"
s3fs-version = "2024.9.0"
cyclonedx-bom-version = "6.0.0"
tini-version = "0.19.0"
uv-version = "0.7.8"
airflow-extras = "async,amazon,celery,cncf.kubernetes,docker,dask,elasticsearch,ftp,grpc,hashicorp,http,ldap,google,google_auth,microsoft.azure,odbc,pandas,postgres,redis,sendgrid,sftp,slack,ssh,statsd,virtualenv,trino"
opa-auth-manager = "airflow-2"
nodejs-version = "20"

[versions."2.10.5".local-images]
"shared/statsd-exporter" = "0.28.0"
vector = "0.49.0"
stackable-devel = "1.0.0"

[versions."2.10.5".build-arguments]
python-version = "3.12"
git-sync-version = "v4.4.1"
s3fs-version = "2024.9.0"
cyclonedx-bom-version = "6.0.0"
tini-version = "0.19.0"
uv-version = "0.7.8"
airflow-extras = "async,amazon,celery,cncf.kubernetes,docker,dask,elasticsearch,ftp,grpc,hashicorp,http,ldap,google,google_auth,microsoft.azure,odbc,pandas,postgres,redis,sendgrid,sftp,slack,ssh,statsd,virtualenv,trino"
opa-auth-manager = "airflow-2"
nodejs-version = "20"

[versions."3.0.1".local-images]
"shared/statsd-exporter" = "0.28.0"
vector = "0.49.0"
stackable-devel = "1.0.0"

[versions."3.0.1".build-arguments]
python-version = "3.12"
git-sync-version = "v4.4.1"
s3fs-version = "2024.9.0"
cyclonedx-bom-version = "6.0.0"
tini-version = "0.19.0"
uv-version = "0.7.8"
airflow-extras = "airbyte,alibaba,amazon,apache-beam,apache-cassandra,apache-drill,apache-druid,apache-flink,apache-hdfs,apache-hive,apache-iceberg,apache-impala,apache-kafka,apache-kylin,apache-livy,apache-pig,apache-pinot,apache-spark,apprise,arangodb,asana,atlassian-jira,celery,cloudant,cncf-kubernetes,cohere,common-compat,common-io,common-messaging,common-sql,databricks,datadog,dbt-cloud,dingding,discord,docker,edge3,elasticsearch,exasol,fab,facebook,ftp,git,github,google,grpc,hashicorp,http,imap,influxdb,jdbc,jenkins,microsoft-azure,microsoft-mssql,microsoft-psrp,microsoft-winrm,mongo,neo4j,odbc,openai,openfaas,openlineage,opensearch,opsgenie,oracle,pagerduty,papermill,pgvector,pinecone,postgres,presto,qdrant,redis,salesforce,samba,segment,sendgrid,sftp,singularity,slack,smtp,snowflake,sqlite,ssh,standard,tableau,telegram,teradata,trino,vertica,weaviate,yandex,ydb,zendesk"
opa-auth-manager = "airflow-3"
nodejs-version = "20"

[versions."3.0.6".local-images]
"shared/statsd-exporter" = "0.28.0"
vector = "0.49.0"
stackable-devel = "1.0.0"

[versions."3.0.6".build-arguments]
python-version = "3.12"
git-sync-version = "v4.4.1"
s3fs-version = "2024.9.0"
cyclonedx-bom-version = "6.0.0"
tini-version = "0.19.0"
uv-version = "0.7.8"
airflow-extras = "airbyte,alibaba,amazon,apache-beam,apache-cassandra,apache-drill,apache-druid,apache-flink,apache-hdfs,apache-hive,apache-iceberg,apache-impala,apache-kafka,apache-kylin,apache-livy,apache-pig,apache-pinot,apache-spark,apprise,arangodb,asana,atlassian-jira,celery,cloudant,cncf-kubernetes,cohere,common-compat,common-io,common-messaging,common-sql,databricks,datadog,dbt-cloud,dingding,discord,docker,edge3,elasticsearch,exasol,fab,facebook,ftp,git,github,google,grpc,hashicorp,http,imap,influxdb,jdbc,jenkins,microsoft-azure,microsoft-mssql,microsoft-psrp,microsoft-winrm,mongo,neo4j,odbc,openai,openfaas,openlineage,opensearch,opsgenie,oracle,pagerduty,papermill,pgvector,pinecone,postgres,presto,qdrant,redis,salesforce,samba,segment,sendgrid,sftp,singularity,slack,smtp,snowflake,sqlite,ssh,standard,tableau,telegram,teradata,trino,vertica,weaviate,yandex,ydb,zendesk"
opa-auth-manager = "airflow-3"
nodejs-version = "20"
