[versions."2.9.3".local-images]
"shared/statsd-exporter" = "0.28.0"
vector = "0.49.0"
stackable-devel = "1.0.0"

[versions."2.9.3".build-arguments]
python-version = "3.9"
git-sync-version = "v4.4.1"
s3fs-version = "2024.9.0"
cyclonedx-bom-version = "6.0.0"
tini-version = "0.19.0"
uv-version = "0.7.8"
airflow-extras = "async,amazon,celery,cncf.kubernetes,docker,dask,elasticsearch,ftp,grpc,hashicorp,http,ldap,google,google_auth,microsoft.azure,odbc,pandas,postgres,redis,sendgrid,sftp,slack,ssh,statsd,virtualenv,trino"
opa-auth-manager = "airflow-2"
nodejs-version = "20"

[versions."2.10.5".local-images]
"shared/statsd-exporter" = "0.28.0"
vector = "0.49.0"
stackable-devel = "1.0.0"

[versions."2.10.5".build-arguments]
python-version = "3.12"
git-sync-version = "v4.4.1"
s3fs-version = "2024.9.0"
cyclonedx-bom-version = "6.0.0"
tini-version = "0.19.0"
uv-version = "0.7.8"
airflow-extras = "async,amazon,celery,cncf.kubernetes,docker,dask,elasticsearch,ftp,grpc,hashicorp,http,ldap,google,google_auth,microsoft.azure,odbc,pandas,postgres,redis,sendgrid,sftp,slack,ssh,statsd,virtualenv,trino"
opa-auth-manager = "airflow-2"
nodejs-version = "20"

[versions."3.0.1".local-images]
"shared/statsd-exporter" = "0.28.0"
vector = "0.49.0"
stackable-devel = "1.0.0"

[versions."3.0.1".build-arguments]
python-version = "3.12"
git-sync-version = "v4.4.1"
s3fs-version = "2024.9.0"
cyclonedx-bom-version = "6.0.0"
tini-version = "0.19.0"
uv-version = "0.7.8"
airflow-extras = "async,amazon,celery,cncf-kubernetes,docker,elasticsearch,fab,ftp,grpc,hashicorp,http,ldap,google,microsoft-azure,odbc,pandas,postgres,redis,sendgrid,sftp,slack,ssh,statsd,trino"
opa-auth-manager = "airflow-3"
nodejs-version = "20"

[versions."3.0.6".local-images]
"shared/statsd-exporter" = "0.28.0"
vector = "0.49.0"
stackable-devel = "1.0.0"

[versions."3.0.6".build-arguments]
python-version = "3.12"
git-sync-version = "v4.4.1"
s3fs-version = "2024.9.0"
cyclonedx-bom-version = "6.0.0"
tini-version = "0.19.0"
uv-version = "0.7.8"
airflow-extras = "amazon,apache-druid,apache-flink,apache-hdfs,apache-hive,apache-iceberg,apache-kafka,apache-webhdfs,async,celery,cncf-kubernetes,common-messaging,databricks,datadog,discord,docker,elasticsearch,exasol,fab,ftp,google,grpc,hashicorp,http,influxdb,kerberos,ldap,microsoft-azure,mongodb,neo4,odbc,openai,opsgenie,oracle,otel,pandas,polars,postgres,rabbitmq,redis,salesforce,sendgrid,sftp,slack,ssh,statsd,tableau,teradata,trino"
opa-auth-manager = "airflow-3"
nodejs-version = "20"
