[versions."0.52.0".local-images]
# We need to point to a special version of stackable-devel which will have the
# correct toolchain to build vector.
stackable-devel = "vector-build"
stackable-base = "1.0.0"

[versions."0.52.0".build-arguments]
# See .scripts/upload_new_protoc_version.sh
# Unsure which version is used by vector. They seem to install `buf` in workflows.
protoc-version = "31.1"
# See here: https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/i/
# Note: In UBI10, this should change to 4.23.9.0-4.el10
inotify-tools = "3.22.1.0-1.el9"
rpm-release = "1"
