[versions."3.1.0.0".local-images]
java-devel = "21"

[versions."3.4.0.0".local-images]
# OpenSearch 3.4.0 bundles JDK 24, but the OpenSearch Prometheus Exporter can only be built with
# JDK 21.
java-devel = "21"
