[versions."1.0.0"]

# Used specifically by vector
[versions."vector-build".build-arguments]
# Use what upstream vector uses:
# https://github.com/vectordotdev/vector/blob/v0.52.0/rust-toolchain.toml
rust-default-toolchain-version = "1.91.1"
