[versions."3.3.6".local-images]
java-devel = "11"

[versions."3.3.6".build-arguments]
protobuf-version = "3.7.1"

[versions."3.4.2".local-images]
java-devel = "11"

[versions."3.4.2".build-arguments]
protobuf-version = "3.7.1"
