[versions."v1.0.0-hive-3.1.3-hadoop-3.3.6".local-images]
"java-devel" = "11"

[versions."v1.0.0-hive-3.1.3-hadoop-3.3.6".build-arguments]
authorizer-version = "v1.0.0"
hive-version = "3.1.3"
hadoop-version = "3.3.6"
delete-caches = "true"

[versions."v1.0.0-hive-4.0.1-hadoop-3.3.6".local-images]
"java-devel" = "11"

[versions."v1.0.0-hive-4.0.1-hadoop-3.3.6".build-arguments]
authorizer-version = "v1.0.0"
hive-version = "4.0.1"
hadoop-version = "3.3.6"
delete-caches = "true"

[versions."v1.0.0-hive-4.1.0-hadoop-3.4.2".local-images]
"java-devel" = "17"

[versions."v1.0.0-hive-4.1.0-hadoop-3.4.2".build-arguments]
authorizer-version = "v1.0.0"
hive-version = "4.1.0"
hadoop-version = "3.4.2"
delete-caches = "true"
