
[versions."1.0.1_3.5.7".local-images]
java-devel = "17"

[versions."1.0.1_3.5.7".build-arguments]
spark-version = "3.5.7"
hadoop-version = "3.4.2"
hbase-version = "2.6.3"

[versions."1.0.1_3.5.8".local-images]
java-devel = "17"

[versions."1.0.1_3.5.8".build-arguments]
spark-version = "3.5.8"
hadoop-version = "3.4.2"
hbase-version = "2.6.3"
