[versions."1.2.13".local-images]
java-devel = "8"

[versions."1.3.14".local-images]
java-devel = "21"

[versions."1.3.15".local-images]
java-devel = "21"

[versions."1.5.18".local-images]
java-devel = "21"

[versions."1.5.24".local-images]
java-devel = "21"
