---
name: Release boil

on:
  push:
    tags:
      - "boil-[0-9]+.[0-9]+.[0-9]+**"

env:
  RUST_VERSION: 1.92.0

jobs:
  create-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        uses: orhun/git-cliff-action@e16f179f0be49ecdfe63753837f20b9531642772 # v4.7.0
        with:
          config: rust/boil/cliff.toml
          args: --latest --strip header

      - name: Create Draft Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          body: ${{ steps.changelog.outputs.content }}
          draft: true

  build:
    name: Build boil
    needs: [create-release]
    strategy:
      fail-fast: false
      matrix:
        targets:
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-24.04-arm }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: aarch64-apple-darwin, os: macos-latest }
    runs-on: ${{ matrix.targets.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.targets.target }}

      - name: Build Binary
        env:
          TARGET: ${{ matrix.targets.target }}
        run: cargo build --target "$TARGET" --release --package boil

      - name: Rename Binary
        env:
          TARGET: ${{ matrix.targets.target }}
        run: mv "target/$TARGET/release/boil" "boil-$TARGET"

      - name: Upload Artifact to Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: boil-${{ matrix.targets.target }}
          draft: true

  finish-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Finish Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          draft: false
