---
name: Release boil

on:
  push:
    tags:
      - "boil-[0-9]+.[0-9]+.[0-9]+**"

env:
  RUST_VERSION: 1.89.0

jobs:
  create-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        uses: orhun/git-cliff-action@d77b37db2e3f7398432d34b72a12aa3e2ba87e51 # v4.6.0
        with:
          config: rust/boil/cliff.toml
          args: --latest --strip header

      - name: Create Draft Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          body: ${{ steps.changelog.outputs.content }}
          draft: true

  build:
    name: Build boil
    needs:
      - create-release
    strategy:
      fail-fast: false
      matrix:
        targets:
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-24.04-arm }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: aarch64-apple-darwin, os: macos-latest }
    runs-on: ${{ matrix.targets.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.targets.target }}

      - name: Build Binary
        env:
          TARGET: ${{ matrix.targets.target }}
        run: cargo build --target "$TARGET" --release --package boil

      - name: Rename Binary
        env:
          TARGET: ${{ matrix.targets.target }}
        run: mv "target/$TARGET/release/boil" "boil-$TARGET"

      - name: Upload Artifact to Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          draft: false
          files: boil-${{ matrix.targets.target }}
